GET  http://localhost:3000/api/products

###

GET http://localhost:3000/api/products/655fbe6c749d44e72234a058

###

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Shirt 2",
    "price": 15.30,
    "supplier": "655f0bb82706558f30933e01",
    "rating": 4.5,
    "description": "A nice shirt. It's red. It's a shirt. What more do you want?    "
}

###

DELETE http://localhost:4000/api/suppliers/655f0bb82706558f30933e01


###
PATCH http://localhost:4000/api/suppliers/655f0bb82706558f30933e01
Content-Type: application/json

{
    "email": "tuya@gmail.com"
}
