GET  http://localhost:3000/api/suppliers

###

GET http://localhost:3000/api/products/655fbe6c749d44e72234a058

###

POST http://localhost:3000/api/products
Content-Type: application/json


###
POST http://localhost:3000/api/suppliers
Content-Type: application/json

{
    "name": "Jake Smith",
    "email": "jake@email.com",
    "phoneNumber": "0768553156",
    "password": "123456",
    
}

###

GET http://localhost:3000/api/products/search/sunglasses


###
PATCH http://localhost:4000/api/suppliers/655f0bb82706558f30933e01
Content-Type: application/json

{
    "email": "tuya@gmail.com"
}
